# Build an Agent

ref. [Build an Agent \| 🦜️🔗 LangChain](https://python.langchain.com/docs/tutorials/agents/)

> Agents are systems that take a high-level task and use an LLM as a reasoning engine to decide what actions to take and execute those actions.

> We recommend that you use LangGraph for building agents.

- [Agent architectures](https://langchain-ai.github.io/langgraph/concepts/agentic_concepts/)
- [Pre-built agents in LangGraph](https://langchain-ai.github.io/langgraph/reference/prebuilt/)

This is often achieved via tool-calling.
- [Tool calling \| 🦜️🔗 LangChain](https://python.langchain.com/docs/concepts/tool_calling/)

## End-to-end agent


### Installation (Additional packages)

ref. LangChain Ecosystem: [How to install LangChain packages \| 🦜️🔗 LangChain](https://python.langchain.com/docs/how_to/installation/)

**Integration packages**

- **langchain-community**:
  - This package contains integrations that haven't been split out into their own packages.
  - It serves as a community-driven collection of tools and utilities for LangChain.
- **langgraph**:
  - It includes functionalities for creating, querying, and visualizing graphs.
- **langgraph-checkpoint-sqlite**:
  - This package provides checkpointing capabilities for LangGraph using SQLite as the backend.
  - It allows users to save and restore the state of their knowledge graphs efficiently.
- **tavily-python**:
  - This package offers Python bindings for Tavily, a tool or library that is part of the LangChain ecosystem.
  - It provides functionalities specific to Tavily's use cases and integrations.

> Any integrations that haven't been split out into their own packages will live in the langchain-community package.

<img src="https://python.langchain.com/assets/images/ecosystem_packages-32943b32657e7a187770c9b585f22a64.png" width="720" style="background-color: white;">

### LangSmith & Tavily

In [1]:
import os

os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGCHAIN_PROJECT"] = "langchain-tutorials"

[Tavily Search \| 🦜️🔗 LangChain](https://python.langchain.com/docs/integrations/tools/tavily_search/)

[Tavily AI | Home](https://app.tavily.com/home)

⚠️ **<span style="color:red;">1,000 Requests / Month</span>** (Free plan)

It's increasing by **2** per TavilyTool use.

`.env`

```
LANGCHAIN_API_KEY=**********
TAVILY_API_KEY=**********
```

In [2]:
from dotenv import load_dotenv

load_dotenv(dotenv_path="../.env")

True

## Define tools

Use Tavily to search for information.

API Reference: [TavilySearchResults — 🦜🔗 LangChain documentation](https://python.langchain.com/api_reference/community/tools/langchain_community.tools.tavily_search.tool.TavilySearchResults.html)

In [3]:
from langchain_community.tools.tavily_search import TavilySearchResults

search = TavilySearchResults(max_results=2)
search_results = search.invoke("what is the weather in Spa-Francorchamps?")
print(search_results)

# If we want, we can create other tools.
# Once we have all the tools we want, we can put them in a list that we will reference later.
tools = [search]

[{'url': 'https://www.weatherapi.com/', 'content': "{'location': {'name': 'Francorchamps', 'region': '', 'country': 'Belgium', 'lat': 50.45, 'lon': 5.95, 'tz_id': 'Europe/Brussels', 'localtime_epoch': 1733507665, 'localtime': '2024-12-06 18:54'}, 'current': {'last_updated_epoch': 1733507100, 'last_updated': '2024-12-06 18:45', 'temp_c': 3.2, 'temp_f': 37.8, 'is_day': 0, 'condition': {'text': 'Partly cloudy', 'icon': '//cdn.weatherapi.com/weather/64x64/night/116.png', 'code': 1003}, 'wind_mph': 9.2, 'wind_kph': 14.8, 'wind_degree': 265, 'wind_dir': 'W', 'pressure_mb': 1017.0, 'pressure_in': 30.03, 'precip_mm': 0.03, 'precip_in': 0.0, 'humidity': 93, 'cloud': 75, 'feelslike_c': -0.4, 'feelslike_f': 31.2, 'windchill_c': 0.2, 'windchill_f': 32.3, 'heatindex_c': 3.7, 'heatindex_f': 38.7, 'dewpoint_c': 2.8, 'dewpoint_f': 37.0, 'vis_km': 10.0, 'vis_miles': 6.0, 'uv': 0.0, 'gust_mph': 13.6, 'gust_kph': 21.9}}"}, {'url': 'https://weather.metoffice.gov.uk/forecast/u0unzv6ce', 'content': 'Spa F10

e.g.
```
[{'url': 'https://www.weatherapi.com/', 'content': "{'location': {'name': 'Francorchamps', 'region': '', 'country': 'Belgium', 'lat': 50.45, 'lon': 5.95, 'tz_id': 'Europe/Brussels', 'localtime_epoch': 1733404633, 'localtime': '2024-01-01 23:59'}, 'current': {'last_updated_epoch': 1733404500, 'last_updated': '2024-01-01 23:59', 'temp_c': 1.2, 'temp_f': 34.2, 'is_day': 1, 'condition': {'text': 'Light rain', 'icon': '//cdn.weatherapi.com/weather/64x64/day/296.png', 'code': 1183}, 'wind_mph': 17.2, 'wind_kph': 27.7, 'wind_degree': 184, 'wind_dir': 'S', 'pressure_mb': 1015.0, 'pressure_in': 29.97, 'precip_mm': 0.36, 'precip_in': 0.01, 'humidity': 93, 'cloud': 100, 'feelslike_c': -4.7, 'feelslike_f': 23.6, 'windchill_c': -3.9, 'windchill_f': 25.0, 'heatindex_c': 1.8, 'heatindex_f': 35.3, 'dewpoint_c': 0.8, 'dewpoint_f': 33.4, 'vis_km': 5.0, 'vis_miles': 3.0, 'uv': 0.1, 'gust_mph': 27.8, 'gust_kph': 44.8}}"}, {'url': 'https://gpweather.com/f1/2024/belgium', 'content': 'Complete weather forecast for the F1 2024 Belgian Grand Prix. Get real-time updates on weather conditions and stay up-to-date with the latest forecasts. GP. Weather. ... Spa-Francorchamps circuit. Current weather situation and precipitation forecast. (night) Rain. 0% 0.0mm. Wind. Humidity. 84.4 %. Clouds. 3 %. Pressure. 1025.4 hPa. Visibility.'}]
```

## Using Language Models

Model: Try to use Anthropic's models in this notebook.
- **langchain-anthropic**:
  - For Anthropic's AI models (e.g. Claude)

See: [Anthropic Console](https://console.anthropic.com/dashboard)

`.env`

```
ANTHROPIC_API_KEY=**********
```

In [4]:
load_dotenv(dotenv_path="../.env")

True

In [5]:
from langchain_anthropic import ChatAnthropic

model = ChatAnthropic(model="claude-3-5-sonnet-20240620")

In [6]:
from langchain_core.messages import HumanMessage

response = model.invoke([HumanMessage(content="hi!")])
response.content  # By default, the response is a content string.

'Hello! How can I assist you today? Feel free to ask me any questions or let me know if you need help with anything.'

See: LangSmith

e.g.

ChatAnthropic: Raw Input
```yaml
messages:
  - - lc: 1
      type: constructor
      id:
        - langchain
        - schema
        - messages
        - HumanMessage
      kwargs:
        content: hi!
        type: human
```

ChatAnthropic: Raw Output
```yaml
generations:
  - - text: Hello! How can I assist you today? Feel free to ask any questions or let me know if there's anything specific you'd like help with.
      generation_info: null
      type: ChatGeneration
      message:
        lc: 1
        type: constructor
        id:
          - langchain
          - schema
          - messages
          - AIMessage
        kwargs:
          content: Hello! How can I assist you today? Feel free to ask any questions or let me know if there's anything specific you'd like help with.
          response_metadata:
            id: msg_01RSzg1jq5z3AoTuirnuS3qb
            model: claude-3-5-sonnet-20240620
            stop_reason: end_turn
            stop_sequence: null
            usage:
              input_tokens: 9
              output_tokens: 33
          type: ai
          id: run-c1b89b2e-49d9-4e20-9a28-16b466edc938-0
          usage_metadata:
            input_tokens: 9
            output_tokens: 33
            total_tokens: 42
            input_token_details: {}
          tool_calls: []
          invalid_tool_calls: []
llm_output:
  id: msg_01RSzg1jq5z3AoTuirnuS3qb
  model: claude-3-5-sonnet-20240620
  stop_reason: end_turn
  stop_sequence: null
  usage:
    input_tokens: 9
    output_tokens: 33
run: null
type: LLMResult
```

Give the language model knowledge of these tools.

In [7]:
model_with_tools = model.bind_tools(tools)

### Give message NOT to use Tool

In [8]:
response = model_with_tools.invoke([HumanMessage(content="Hi!")])

print(f"ContentString: {response.content}")
print(f"ToolCalls: {response.tool_calls}")

ContentString: Hello! Welcome. How can I assist you today? I'm here to help with any questions or tasks you might have. Is there something specific you'd like to know or discuss?
ToolCalls: []


### Now, try calling it with some input that would expect a tool to be called

In [9]:
response = model_with_tools.invoke([HumanMessage(content="What's the weather in Spa-Francorchamps?")])

print(f"ContentString: {response.content}")
print(f"ToolCalls: {response.tool_calls}")

ContentString: [{'text': "To answer your question about the weather in Spa-Francorchamps, I'll need to search for current information. Let me do that for you.", 'type': 'text'}, {'id': 'toolu_015CQtCTToZYeLSboRV9jzz8', 'input': {'query': 'current weather in Spa-Francorchamps Belgium'}, 'name': 'tavily_search_results_json', 'type': 'tool_use'}]
ToolCalls: [{'name': 'tavily_search_results_json', 'args': {'query': 'current weather in Spa-Francorchamps Belgium'}, 'id': 'toolu_015CQtCTToZYeLSboRV9jzz8', 'type': 'tool_call'}]


In [10]:
response = model_with_tools.invoke([HumanMessage(content="What's the weather in San Francisco?")])

print(f"ContentString: {response.content}")
print(f"ToolCalls: {response.tool_calls}")

ContentString: I apologize, but I don't have a specific weather function available to provide real-time weather information for San Francisco. However, I can use the search function to find recent weather reports or forecasts for San Francisco. Would you like me to do that?
ToolCalls: []


### Note

e.g. (format modified)
```
ContentString: [
  {
    'text': "To answer your question about the weather in Spa-Francorchamps, I'll need to use a search tool to find the most up-to-date information. Let me do that for you.",
    'type': 'text'
  },
  {
    'id': 'toolu_015PGxS1tMQHs9yAfigDG1om',
    'input': {
      'query': 'current weather in Spa-Francorchamps, Belgium'
    },
    'name': 'tavily_search_results_json',
    'type': 'tool_use'
  }
]

ToolCalls: [
  {
    'name': 'tavily_search_results_json',
    'args': {
      'query': 'current weather in Spa-Francorchamps, Belgium'
    },
    'id': 'toolu_015PGxS1tMQHs9yAfigDG1om',
    'type': 'tool_call'
  }
]
```

> We can see that there's now no text content, but there is a tool call! It wants us to call the Tavily Search tool.

> This isn't calling that tool yet - it's just telling us to. In order to actually call it, we'll want to create our agent.

-> 🤔 I can see the text content.


In [11]:
response = model_with_tools.invoke([HumanMessage(content="What's the weather in SF?")])

print(f"ContentString: {response.content}")
print(f"ToolCalls: {response.tool_calls}")

ContentString: I apologize, but I don't have access to real-time weather information for San Francisco or any other location. The tools available to me don't include a weather service. 

However, I can search for recent weather information about San Francisco using the search function. Would you like me to do that?
ToolCalls: []


**Note*

e.g.
```
ContentString: I apologize, but I don't have access to real-time weather information for San Francisco or any other location. The tools available to me don't include a weather service. However, I can help you find current weather information for San Francisco using a search engine. Would you like me to search for that information?
ToolCalls: []
```

And sometimes Span-Francorchamps is same as SF.:
```
ContentString: I apologize, but I don't have a specific weather tool available to directly check the current weather conditions in Spa-Francorchamps. However, I can search for recent weather information about this location using the search function available to me. Would you like me to do that?
ToolCalls: []
```

> We can see that there's now no text content, but there is a tool call! It wants us to call the Tavily Search tool.

-> 🤔 I can see the text content and empty tool call in spite of the weather question.

## Create the Agent

> We will be using [LangGraph](https://python.langchain.com/docs/concepts/architecture/#langgraph) to construct the agent.

> highly controllable API in case you want to modify the agent logic.

passing in the model, NOT model_with_tools.
That is because `create_react_agent` will call `.bind_tools` for us under the hood.

API Reference: [create_react_agent](https://langchain-ai.github.io/langgraph/reference/prebuilt/#langgraph.prebuilt.chat_agent_executor.create_react_agent)

In [12]:
from langgraph.prebuilt import create_react_agent

agent_executor = create_react_agent(model, tools)

## Run the agent

⚠️ Note

- These are all stateless queries as long as no setting. (it doesn't remember any previous interactions).
- The agent returns a final state at the end of the interaction.
  - How to obtain only the outputs will be explained later.

### No need to call a tool

In [13]:
response = agent_executor.invoke({"messages": [HumanMessage(content="hi!")]})

response["messages"]

[HumanMessage(content='hi!', additional_kwargs={}, response_metadata={}, id='30d3d9bb-31ea-4959-94ec-2f2b63f4dc45'),
 AIMessage(content="Hello! It's nice to meet you. How can I assist you today? I'm here to help with a wide range of topics and questions. Is there anything specific you'd like to know or discuss?", additional_kwargs={}, response_metadata={'id': 'msg_01GAkGJ4iMjaJSVdGA7JS3AT', 'model': 'claude-3-5-sonnet-20240620', 'stop_reason': 'end_turn', 'stop_sequence': None, 'usage': {'input_tokens': 399, 'output_tokens': 45}}, id='run-d6c7b13f-74a4-4250-bd39-b238dffb05c2-0', usage_metadata={'input_tokens': 399, 'output_tokens': 45, 'total_tokens': 444, 'input_token_details': {}})]

See: LangSmith

```
LangGraph
      2.29s 444
    __start__
          0.00s graph:step:0
        agent
              2.29s 444 graph:step:1
            call_model
                  2.28s 444 seq:step:1
                RunnableSequence
                      2.28s 444 seq:step:1
                    StateModifier
                          0.00s seq:step:1
                    ChatAnthropic claude-3-5-sonnet-20240620
                          2.27s 444 seq:step:2
            ChannelWrite<agent,messages>
                  0.00s seq:step:2
            should_continue
                  0.00s seq:step:4
```

e.g.

LangSmith: Raw Input

```yaml
messages:
  - content: hi!
    additional_kwargs: {}
    response_metadata: {}
    type: human
    id: 9fbc9581-805a-41a0-8b9a-1853a9a665a1
    example: false
```

LangSmith: Raw Output

```yaml
messages:
  - content: hi!
    additional_kwargs: {}
    response_metadata: {}
    type: human
    id: 9fbc9581-805a-41a0-8b9a-1853a9a665a1
    example: false
  - content: Hello! It's nice to meet you. How can I assist you today? I'm here to help with any questions or tasks you might have. Is there something specific you'd like to know or discuss?
    additional_kwargs: {}
    response_metadata:
      id: msg_012FxjjJ8UhKAsJcBesYiR6G
      model: claude-3-5-sonnet-20240620
      stop_reason: end_turn
      stop_sequence: null
      usage:
        input_tokens: 399
        output_tokens: 45
    type: ai
    id: run-515db302-bca7-484e-abe5-48d6176d5a5e-0
    example: false
    tool_calls: []
    invalid_tool_calls: []
    usage_metadata:
      input_tokens: 399
      output_tokens: 45
      total_tokens: 444
      input_token_details: {}
```

e.g.

agent: Raw Input
```yaml
messages:
  - content: hi!
    additional_kwargs: {}
    response_metadata: {}
    type: human
    id: 9fbc9581-805a-41a0-8b9a-1853a9a665a1
    example: false
is_last_step: false
remaining_steps: 24
```

agent: Raw Output
```yaml
messages:
  - content: Hello! It's nice to meet you. How can I assist you today? I'm here to help with any questions or tasks you might have. Is there something specific you'd like to know or discuss?
    additional_kwargs: {}
    response_metadata:
      id: msg_012FxjjJ8UhKAsJcBesYiR6G
      model: claude-3-5-sonnet-20240620
      stop_reason: end_turn
      stop_sequence: null
      usage:
        input_tokens: 399
        output_tokens: 45
    type: ai
    id: run-515db302-bca7-484e-abe5-48d6176d5a5e-0
    example: false
    tool_calls: []
    invalid_tool_calls: []
    usage_metadata:
      input_tokens: 399
      output_tokens: 45
      total_tokens: 444
      input_token_details: {}
```

e.g.

should_continue: Raw Output

```yaml
output: __end__
```

### Invoking the tool

In [14]:
response = agent_executor.invoke(
    {"messages": [HumanMessage(content="whats the weather in Spa-Francorchamps?")]}
)
response["messages"]

[HumanMessage(content='whats the weather in Spa-Francorchamps?', additional_kwargs={}, response_metadata={}, id='a251111e-984d-4f41-b845-902cffafe111'),
 AIMessage(content="I apologize, but I don't have a specific weather tool available to directly check the current weather in Spa-Francorchamps. However, I can use the search function to find recent weather information for that location. Would you like me to do that?", additional_kwargs={}, response_metadata={'id': 'msg_01Rw8ovu8hsunJaXBjrtQMRj', 'model': 'claude-3-5-sonnet-20240620', 'stop_reason': 'end_turn', 'stop_sequence': None, 'usage': {'input_tokens': 411, 'output_tokens': 58}}, id='run-a5b3f7f7-afb7-4a45-9c0b-68e60f4cb42b-0', usage_metadata={'input_tokens': 411, 'output_tokens': 58, 'total_tokens': 469, 'input_token_details': {}})]

**Note**

e.g.

```
[HumanMessage(content='whats the weather in Spa-Francorchamps?', additional_kwargs={}, response_metadata={}, id='4f05a8db-b22a-4b8e-a782-c1890afdb917'),
 AIMessage(content="I apologize, but I don't have a specific weather function available to directly check the current weather in Spa-Francorchamps. However, I can use the search function to find recent weather information for that location. Would you like me to search for the current weather in Spa-Francorchamps?", additional_kwargs={}, response_metadata={'id': 'msg_01Kijbrvg9iDAWo6V92arDf1', 'model': 'claude-3-5-sonnet-20240620', 'stop_reason': 'end_turn', 'stop_sequence': None, 'usage': {'input_tokens': 411, 'output_tokens': 70}}, id='run-ca42ac7a-5e57-4614-aacc-063d72be6759-0', usage_metadata={'input_tokens': 411, 'output_tokens': 70, 'total_tokens': 481, 'input_token_details': {}})]
```

In some previous cells, there was a ToolCall, but I don't see it in the output here.

🤔 I would guess that the prompt is bad.

In [15]:
response = agent_executor.invoke(
    {"messages": [HumanMessage(content="tell me about Spa-Francorchamps weather.")]}
)
response["messages"]

[HumanMessage(content='tell me about Spa-Francorchamps weather.', additional_kwargs={}, response_metadata={}, id='254ae376-2370-4854-b758-539f27e155ba'),
 AIMessage(content=[{'text': "Certainly! To provide you with accurate and up-to-date information about the weather at Spa-Francorchamps, I'll need to search for the most recent data. Let me use the search tool to find this information for you.", 'type': 'text'}, {'id': 'toolu_01GyYCJEWR9hiePrRjduhWpz', 'input': {'query': 'Spa-Francorchamps current weather conditions'}, 'name': 'tavily_search_results_json', 'type': 'tool_use'}], additional_kwargs={}, response_metadata={'id': 'msg_01WffLxMjwQtGAD7aPvpZrpt', 'model': 'claude-3-5-sonnet-20240620', 'stop_reason': 'tool_use', 'stop_sequence': None, 'usage': {'input_tokens': 410, 'output_tokens': 121}}, id='run-042f323f-022d-4b5d-9d6e-ceb461b45b25-0', tool_calls=[{'name': 'tavily_search_results_json', 'args': {'query': 'Spa-Francorchamps current weather conditions'}, 'id': 'toolu_01GyYCJEWR9

-> OK!!

✅ In the end, it must be all about the prompts to make the LLM work.

See: LangSmith

e.g.
```
LangGraph
      16.48s 2,106
    __start__
          0.00s graph:step:0
    agent
          2.93s 531 graph:step:1
        call_model
              2.92s 531 seq:step:1
            RunnableSequence
                  2.92s 531 seq:step:1
                StateModifier
                      0.00s seq:step:1
                ChatAnthropic claude-3-5-sonnet-20240620
                      2.92s 531 seq:step:2
        ChannelWrite<agent,messages>
              0.00s seq:step:2
        should_continue
              0.00s seq:step:4
    tools
          3.39s graph:step:2
        tavily_search_results_json
              3.39s seq:step:1
        ChannelWrite<tools,messages>
              0.00s seq:step:2
    agent
          10.16s 1,575 graph:step:3
        call_model
              10.15s 1,575 seq:step:1
            RunnableSequence
                  10.15s 1,575 seq:step:1
                StateModifier
                      0.00s seq:step:1
                ChatAnthropic claude-3-5-sonnet-20240620
                      10.15s 1,575 seq:step:2
        ChannelWrite<agent,messages>
              0.00s seq:step:2
        should_continue
              0.00s seq:step:4
```

e.g.

should_continue (1st): Raw Output

```yaml
output: tools
```

e.g.

agent (1st): Raw Input

```yaml
messages:
  - content: tell me about Spa-Francorchamps weather.
    additional_kwargs: {}
    response_metadata: {}
    type: human
    id: 46e44c6e-3103-4ea8-a88d-5276d002b1db
    example: false
is_last_step: false
remaining_steps: 24
```

agent (1st): Raw Output

```yaml
messages:
  - content:
      - text: Certainly! To provide you with accurate and up-to-date information about the weather at Spa-Francorchamps, I'll need to search for the most recent data. Let me use the search tool to find this information for you.
        type: text
      - id: toolu_01RzC8g2WYmvhH6akrBiHEEg
        input:
          query: Spa-Francorchamps current weather conditions
        name: tavily_search_results_json
        type: tool_use
    additional_kwargs: {}
    response_metadata:
      id: msg_01PJbrHEakrmfN7tcnJzK37E
      model: claude-3-5-sonnet-20240620
      stop_reason: tool_use
      stop_sequence: null
      usage:
        input_tokens: 410
        output_tokens: 121
    type: ai
    id: run-fafd2239-fd0e-476a-b6c0-71693fe3307e-0
    example: false
    tool_calls:
      - name: tavily_search_results_json
        args:
          query: Spa-Francorchamps current weather conditions
        id: toolu_01RzC8g2WYmvhH6akrBiHEEg
        type: tool_call
    invalid_tool_calls: []
    usage_metadata:
      input_tokens: 410
      output_tokens: 121
      total_tokens: 531
      input_token_details: {}
```

e.g.

<details>
<summary>LangSmith: Raw Output</summary>

```yaml
messages:
  - content: tell me about Spa-Francorchamps weather.
    additional_kwargs: {}
    response_metadata: {}
    type: human
    id: 46e44c6e-3103-4ea8-a88d-5276d002b1db
    example: false
  - content:
      - text: Certainly! To provide you with accurate and up-to-date information about the weather at Spa-Francorchamps, I'll need to search for the most recent data. Let me use the search tool to find this information for you.
        type: text
      - id: toolu_01RzC8g2WYmvhH6akrBiHEEg
        input:
          query: Spa-Francorchamps current weather conditions
        name: tavily_search_results_json
        type: tool_use
    additional_kwargs: {}
    response_metadata:
      id: msg_01PJbrHEakrmfN7tcnJzK37E
      model: claude-3-5-sonnet-20240620
      stop_reason: tool_use
      stop_sequence: null
      usage:
        input_tokens: 410
        output_tokens: 121
    type: ai
    id: run-fafd2239-fd0e-476a-b6c0-71693fe3307e-0
    example: false
    tool_calls:
      - name: tavily_search_results_json
        args:
          query: Spa-Francorchamps current weather conditions
        id: toolu_01RzC8g2WYmvhH6akrBiHEEg
        type: tool_call
    invalid_tool_calls: []
    usage_metadata:
      input_tokens: 410
      output_tokens: 121
      total_tokens: 531
      input_token_details: {}
  - content: "[{\"url\": \"https://www.weatherapi.com/\", \"content\": \"{'location': {'name': 'Francorchamps', 'region': '', 'country': 'Belgium', 'lat': 50.45, 'lon': 5.95, 'tz_id': 'Europe/Brussels', 'localtime_epoch': 1733408537, 'localtime': '2024-01-01 23:59'}, 'current': {'last_updated_epoch': 1733408100, 'last_updated': '2024-01-01 23:59', 'temp_c': 1.1, 'temp_f': 34.0, 'is_day': 1, 'condition': {'text': 'Moderate rain', 'icon': '//cdn.weatherapi.com/weather/64x64/day/302.png', 'code': 1189}, 'wind_mph': 16.8, 'wind_kph': 27.0, 'wind_degree': 187, 'wind_dir': 'S', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.51, 'precip_in': 0.02, 'humidity': 100, 'cloud': 100, 'feelslike_c': -4.7, 'feelslike_f': 23.5, 'windchill_c': -3.7, 'windchill_f': 25.4, 'heatindex_c': 1.9, 'heatindex_f': 35.5, 'dewpoint_c': 1.0, 'dewpoint_f': 33.7, 'vis_km': 3.7, 'vis_miles': 2.0, 'uv': 0.0, 'gust_mph': 27.0, 'gust_kph': 43.4}}\"}, {\"url\": \"https://gpweather.com/f1/2024/belgium\", \"content\": \"Complete weather forecast for the F1 2024 Belgian Grand Prix. Get real-time updates on weather conditions and stay up-to-date with the latest forecasts. GP. Weather. ... Spa-Francorchamps circuit. Current weather situation and precipitation forecast. (night) Rain. 0% 0.0mm. Wind. Humidity. 84.4 %. Clouds. 3 %. Pressure. 1025.4 hPa. Visibility.\"}]"
    additional_kwargs: {}
    response_metadata: {}
    type: tool
    name: tavily_search_results_json
    id: a19e67c5-ee07-4599-8a69-2e53674e2756
    tool_call_id: toolu_01RzC8g2WYmvhH6akrBiHEEg
    artifact:
      query: Spa-Francorchamps current weather conditions
      follow_up_questions: null
      answer: null
      images: []
      results:
        - title: Weather in Spa-Francorchamps, Belgium
          url: https://www.weatherapi.com/
          content: "{'location': {'name': 'Francorchamps', 'region': '', 'country': 'Belgium', 'lat': 50.45, 'lon': 5.95, 'tz_id': 'Europe/Brussels', 'localtime_epoch': 1733408537, 'localtime': '2024-01-01 23:59'}, 'current': {'last_updated_epoch': 1733408100, 'last_updated': '2024-01-01 23:59', 'temp_c': 1.1, 'temp_f': 34.0, 'is_day': 1, 'condition': {'text': 'Moderate rain', 'icon': '//cdn.weatherapi.com/weather/64x64/day/302.png', 'code': 1189}, 'wind_mph': 16.8, 'wind_kph': 27.0, 'wind_degree': 187, 'wind_dir': 'S', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.51, 'precip_in': 0.02, 'humidity': 100, 'cloud': 100, 'feelslike_c': -4.7, 'feelslike_f': 23.5, 'windchill_c': -3.7, 'windchill_f': 25.4, 'heatindex_c': 1.9, 'heatindex_f': 35.5, 'dewpoint_c': 1.0, 'dewpoint_f': 33.7, 'vis_km': 3.7, 'vis_miles': 2.0, 'uv': 0.0, 'gust_mph': 27.0, 'gust_kph': 43.4}}"
          score: 0.999753
          raw_content: null
        - title: 2024 F1 Belgian Grand Prix Weather Forecast
          url: https://gpweather.com/f1/2024/belgium
          content: Complete weather forecast for the F1 2024 Belgian Grand Prix. Get real-time updates on weather conditions and stay up-to-date with the latest forecasts. GP. Weather. ... Spa-Francorchamps circuit. Current weather situation and precipitation forecast. (night) Rain. 0% 0.0mm. Wind. Humidity. 84.4 %. Clouds. 3 %. Pressure. 1025.4 hPa. Visibility.
          score: 0.99936384
          raw_content: null
      response_time: 2.5
    status: success
  - content: |-
      Based on the search results, I can provide you with information about the current weather conditions at Spa-Francorchamps. Please note that the data provided is a forecast for a future date (December 5, 2024), which is likely the most recent available information from the weather API. Here's a summary of the weather conditions:

      1. Location: Francorchamps, Belgium
      2. Temperature: 1.1°C (34.0°F)
      3. Condition: Moderate rain
      4. Wind: 27.0 km/h (16.8 mph), coming from the South
      5. Humidity: 100%
      6. Cloud cover: 100%
      7. Visibility: 3.7 km (2.0 miles)
      8. Feels like: -4.7°C (23.5°F) due to wind chill
      9. Precipitation: 0.51 mm (0.02 inches) of rain

      It's important to note that Spa-Francorchamps is known for its unpredictable and rapidly changing weather conditions. The circuit is located in the Ardennes forest region, which can experience microclimates and sudden weather shifts.

      For the upcoming Belgian Grand Prix (as per the second search result), the forecast indicates:

      - Some rain is expected
      - Humidity is predicted to be around 84.4%
      - Cloud cover is expected to be low at 3%
      - Atmospheric pressure is forecasted to be 1025.4 hPa

      Keep in mind that weather conditions can change quickly, especially in this area. If you're planning to attend an event at Spa-Francorchamps or are just curious about the weather for a specific date, it's advisable to check the forecast closer to the time of interest for the most accurate and up-to-date information.
    additional_kwargs: {}
    response_metadata:
      id: msg_01GcTodKgcqzFgdfBMJAayi6
      model: claude-3-5-sonnet-20240620
      stop_reason: end_turn
      stop_sequence: null
      usage:
        input_tokens: 1159
        output_tokens: 416
    type: ai
    id: run-e7b2d4ac-f590-4d14-9ddd-3a227302f6cc-0
    example: false
    tool_calls: []
    invalid_tool_calls: []
    usage_metadata:
      input_tokens: 1159
      output_tokens: 416
      total_tokens: 1575
      input_token_details: {}
```

</details>

### Draw the graph

In [16]:
png_mermaid = agent_executor.get_graph().draw_mermaid_png()
with open("img/agent_tool_graph.png", "wb") as f:
    f.write(png_mermaid)

![agent_tool_graph.png](img/agent_tool_graph.png)

## Streaming Messages

## Streaming tokens

## Adding in memory

## Conclusion

For more information on Agents

- [LangGraph overview](https://langchain-ai.github.io/langgraph/concepts/high_level/#core-principles)
- [LangGraph Academy Course](https://academy.langchain.com/courses/intro-to-langgraph)