[project]
name = "langchain-tutorials"
version = "0.1.0"
description = "Hands-on LangChain official tutorials."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.2.5",
    "langchain>=0.3.2",
]
